client/components/canvas.tsx
client/components/panel.tsx
client/components/whiteboard.tsx
client/routes.js
client/store/Panel.ts
client/store/index.js

Feature: Created Panel Reducer and implemented eraser feature

Feature: Panel Reducer

---

client/components/canvas.tsx
client/components/color.tsx
client/components/whiteboard.tsx
client/store/Panel.ts
package-lock.json
package.json
public/style.css

Feature: Implemented Color Picker component and edited sockets to display proper colors.

Feature: Colors

---

src/auth/index.ts
src/entity/User.ts

Refactor: #30: login API route updated

---

client/components/canvas.tsx
client/components/fabricCanvas.tsx
client/components/navbar.js
client/components/panel.tsx
client/components/whiteboard.tsx
client/store/Panel.ts
package-lock.json
package.json
server/socket/index.ts

Feature: Refactored the code to use FabricJS instead of Canvas HTML5.  Added new features such as clear canvas.

Feature: FabricJS

---

client/routes.js
client/store/user.js
client/store/user.spec.js
src/auth/index.ts
src/index.ts

Bug #37: Update /auth/ routes to send User object

---

client/components/fabricCanvas.tsx
client/components/panel.tsx
src/socket/index.ts

Feature: Added Object Modification, Text, Text Modification, Delete

Feature: Added Object Modification, Text, Text Modification, Delete

---

client/components/fabricCanvas.tsx
client/components/panel.tsx

Feature: User is able to download an image file of the current canvas on click of a button.

Feature: Download Canvas

---

.gitignore
client/components/chat.tsx
client/components/navbar.js
client/components/new-message-entry.tsx
client/components/single-message.tsx
client/routes.js
client/store/Chat.ts
client/store/index.js
client/tsconfig.json
client/types/componentTypes.d.ts
client/types/storeTypes.d.ts
package-lock.json
package.json
public/style.css
src/api/index.ts
src/api/messages.ts
src/auth/index.ts
src/entity/Message.ts
src/entity/User.ts

Mlln chat2

---

client/app.tsx
client/components/fabricCanvas.tsx
client/components/home.tsx
client/components/panel.tsx
client/components/welcome.tsx

Fixed some TS errors and loading errors.

Feature: Fix errors

---

client/components/color.tsx
client/components/panel.tsx
client/components/setRoom.tsx
client/components/welcome.tsx
client/components/whiteboard.tsx
client/store/Panel.ts
package-lock.json
package.json
public/style.css

Created in between page between welcome page and whiteboard

Feature: Waiting Room

---

client/components/color.tsx
client/components/panel.tsx
client/components/whiteboard.tsx
client/store/Panel.ts
public/style.css

Added second color picker for 'fill'.
Styled color picker so that it will only show upon clicking the color picker button.
Styled color pickers to float on top of whiteboard.

Feature: Toggle Color Palette

---

client/components/canvasTools/circle.tsx
client/components/canvasTools/delete.tsx
client/components/canvasTools/draw.tsx
client/components/canvasTools/line.tsx
client/components/canvasTools/modifyObject.tsx
client/components/canvasTools/rectangle.tsx
client/components/canvasTools/text.tsx
client/components/canvasTools/triangle.tsx
client/components/fabricCanvas.tsx
client/components/home.tsx
client/components/navbar.js
client/components/panel.tsx
client/components/welcome.tsx
client/components/whiteboard.tsx

Fixed errors from relocation of import/exports

Fixed relocation errors

---

client/components/buttons/circleButton.tsx
client/components/buttons/clearCanvasButton.tsx
client/components/buttons/colorButton.tsx
client/components/buttons/deleteButton.tsx
client/components/buttons/downloadButton.tsx
client/components/buttons/drawButton.tsx
client/components/buttons/lineButton.tsx
client/components/buttons/rectangleButton.tsx
client/components/buttons/selectButton.tsx
client/components/buttons/shareButton.tsx
client/components/buttons/textButton.tsx
client/components/buttons/triangleButton.tsx
client/components/canvasTools/circle.tsx
client/components/canvasTools/rectangle.tsx
client/components/canvasTools/text.tsx
client/components/canvasTools/triangle.tsx
client/components/color.tsx
client/components/fabricCanvas.tsx
client/components/home.tsx
client/components/panel.tsx
client/components/whiteboard.tsx
package-lock.json
package.json

Added Material-UI buttons to panel

Feature: Panel Material UI

---

client/components/canvasTools/circle.tsx
client/components/canvasTools/rectangle.tsx
client/components/canvasTools/text.tsx
client/components/canvasTools/triangle.tsx
client/components/fabricCanvas.tsx
client/components/home.tsx
client/components/panel.tsx

Feature: added a keydown event listener to delete objects on delete keystroke

feature: delete object when delete button is pressed

---

client/components/fabricCanvas.tsx
client/components/single-message.tsx
client/components/whiteboard.tsx
public/index.html
public/style.css

feature - dynamic messages css

Feature: Dynamic Messages CSS

---

client/components/panel.tsx
public/style.css

feature: buttons stay highlighted / depending on what tool is selected

feature: buttons stay highlighted / depending on what tool is selected

---

client/components/auth-form.js
client/components/canvasTools/circle.tsx
client/components/canvasTools/draw.tsx
client/components/canvasTools/modifyObject.tsx
client/components/canvasTools/rectangle.tsx
client/components/canvasTools/text.tsx
client/components/canvasTools/triangle.tsx
client/components/error-page.tsx
client/components/fabricCanvas.tsx
client/components/panel.tsx
client/components/user-home.tsx
client/types/componentTypes.d.ts
public/index.html
public/style.css
src/socket/index.ts

fix: socketed the rotations for objects on replay and modification

fix: socketed the rotations for objects on replay and modification

---

client/components/auth-form.js
client/components/canvasTools/circle.tsx
client/components/canvasTools/draw.tsx
client/components/canvasTools/modifyObject.tsx
client/components/canvasTools/rectangle.tsx
client/components/canvasTools/text.tsx
client/components/canvasTools/triangle.tsx
client/components/chat.tsx
client/components/error-page.tsx
client/components/fabricCanvas.tsx
client/components/user-home.tsx
client/components/welcome.tsx
client/sockets/chat-sockets.ts
client/store/Chat.ts
client/types/componentTypes.d.ts
public/index.html
src/socket/index.ts

Fix rotation

---

client/components/panel.tsx

Feature: Fix Duplicate Line Tool

---

client/components/navbar.js
client/components/panel.tsx
client/components/welcome.tsx
public/index.html
public/style.css

Added CSS for Welcome and Share Key Button

Feature: Added CSS for Welcome and Share Key Button

---

client/components/auth-form.js
client/components/navbar.js
client/components/welcome.tsx
public/style.css

---
Updated CSS in login and signup and adjusted nav bar

Final touches

---

client/components/create-room-form.tsx
client/components/join-room-form.tsx
client/store/panel-store.ts
public/style.css

Fixed create/join buttons and stroke color picker

Feature: Fixed create/join buttons and stroke color picker

---

client/components/panel.tsx

Commented out line tool for the time being.

Bug:  Line Tool
